name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.0'

    - run: |
        cd VueProject
        yarn install
    - run: |
        cd VueProject
        yarn build --if-present
    - run: |
        cd VueProject
        yarn test
